require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'app/models/settings.rb'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'db/schema.rb'
    - 'vendor/**/**'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

