require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'app/models/settings.rb'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'db/schema.rb'
    - 'vendor/**/**'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20231010092354_create_active_storage_tables.active_storage.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20231010092354_create_active_storage_tables.active_storage.rb'

Style/Documentation:
  Enabled: false

