require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'app/models/settings.rb'
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'db/schema.rb'
    - 'vendor/**/**'

Layout/EmptyLines:
  Exclude:
    - 'config/initializers/new_framework_defaults_7_1.rb'

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'config/environments/production.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'
    - 'config/initializers/filter_parameter_logging.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20231010092354_create_active_storage_tables.active_storage.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20231010092354_create_active_storage_tables.active_storage.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/environments/test.rb'
    - 'config/initializers/assets.rb'
    - 'config/initializers/content_security_policy.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'config/initializers/inflections.rb'
    - 'config/initializers/new_framework_defaults_7_1.rb'
    - 'config/initializers/permissions_policy.rb'

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/application.rb'

Style/RedundantConstantBase:
  Exclude:
    - 'config/environments/production.rb'

Style/StringLiterals:
  Exclude:
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/environments/test.rb'
    - 'config/initializers/assets.rb'

Style/SymbolArray:
  Exclude:
    - 'config/initializers/filter_parameter_logging.rb'

