plugins:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/brakeman'
    - 'bin/bundle'
    - 'bin/dev'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rubocop'
    - 'bin/setup'
    - 'bin/thrust'
    - 'db/schema.rb'
    - 'vendor/**/**'
  NewCops: enable

Layout/LineLength:
  Max: 120

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/consolidation.rb'
    - 'config/environments/production.rb'
    - 'config/initializers/filter_parameter_logging.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20231010092354_create_active_storage_tables.active_storage.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/ParameterLists:
  CountKeywordArgs: false

Minitest/MultipleAssertions:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/environments/consolidation.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/environments/test.rb'
    - 'config/initializers/assets.rb'
    - 'config/initializers/content_security_policy.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'config/initializers/inflections.rb'
    - 'config/initializers/permissions_policy.rb'
    - 'config/puma.rb'
    - 'Gemfile'

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/consolidation.rb'
    - 'config/environments/production.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/application.rb'

Style/RedundantConstantBase:
  Exclude:
    - 'config/environments/consolidation.rb'
    - 'config/environments/production.rb'

Style/StringLiterals:
  Exclude:
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/environments/consolidation.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/environments/test.rb'
    - 'config/initializers/assets.rb'
    - 'config/puma.rb'

Style/SymbolArray:
  Exclude:
    - 'config/initializers/filter_parameter_logging.rb'

