development: &default
  instance:
    name: Klarschiff-MV
    relative_url_root: /
  mailer: 
    interceptions_recipient: to@example.com
    from: from@example.com
    host: example.com
  url:
    imprint: https://www.klarschiff-mv.de/static/imprint
    external_privacy_url: https://www.regierung-mv.de/Datenschutz/

test:
  <<: *default

alpha:
  <<: *default

consolidation:
  <<: *default
  instance:
    name: Klarschiff-MV
    relative_url_root: /participation
  mailer: 
    interceptions_recipient: support-klarschiff@bfpi.de
    from: participation@klarschiff-mv.sis-schwerin.de
    host: klarschiff-mv.sis-schwerin.de

production:
  <<: *default
  instance:
    name: Klarschiff-MV
    relative_url_root: /participation
  mailer: 
    interceptions_recipient:
    from: participation@klarschiff-mv.de
    host: klarschiff-mv.de
