development: &default
  instance: &default_instance
    name: Klarschiff-MV
    relative_url_root: /participation
  mailer: 
    interceptions_recipient: to@example.com
    from: from@example.com
    host: example.com
  url:
    imprint: https://www.klarschiff-mv.de/static/imprint
    external_privacy_url: https://www.regierung-mv.de/Datenschutz/

test:
  <<: *default
  instance:
    <<: *default_instance
    relative_url_root: /

consolidation:
  <<: *default

production:
  <<: *default
