development: &default
  client:
    name: Klarschiff-MV
  mailer: 
    interceptions_recipient: support-klarschiff@bfpi.de
  url:
    imprint: https://www.klarschiff-mv.de/static/imprint
    external_privacy_url: https://www.regierung-mv.de/Datenschutz/

test:
  <<: *default

alpha:
  <<: *default

consolidation:
  <<: *default

production:
  <<: *default
