name: Javascripts

on: [push]

jobs:
  eslint:
    name: Plain JS files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '16'
      - run: bin/eslint
  coffeelint:
    name: Coffee JS files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '16'
      - run: bin/coffeelint
